package br.com.statusnfe.querynfe.portal;

public enum TableOrderEnum {

    AUTORIZADOR,
    AUTORIZACAO4,
    RETORNOAUTORIZACAO4,
    INUTILIZACAO4,
    CONSULTAPROTOCOLO4,
    STATUSSERVICO4,
    TEMPOMEDIO,
    CONSULTACADASTRO4,
    RECEPCAOEVENTO4;
}
